name: arelith_crafting
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  cloud_firestore: ^3.1.17
  file_picker: ^4.6.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  get_it: ^7.2.0
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
