name: arelith_crafting
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.11
  cloud_firestore: ^4.3.1
  file_picker: ^5.2.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  get_it: ^7.2.0
  hive_generator: ^2.0.0
  injectable: ^2.1.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
